# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_CARRIER: [ ROLE_ADMIN ]
        ROLE_SELLER: [ ROLE_ADMIN ]
        ROLE_EMPLOYEE: [ ROLE_SUPER_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    encoders:
        AppBundle\Entity\User:
            algorithm: md5

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class: AppBundle\Entity\User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path:  backend_login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
                path:     /
                always_remember_me: true


    access_control:
        - { path: ^/backend, roles: ROLE_ADMIN }
